### PR TITLE
Add options to convert image files (e.g. to PNG) during upload and delete them after.

### PR DESCRIPTION
**Pull request by riccardomurri**

### CODE REVIEW

**Comment by riccardomurri** [comment]
@sparkvilla This is the PR for implementing the features described in https://trello.com/c/1xms6GFU -- can you please test it and then merge?

**Comment by sparkvilla** [comment]
@riccardomurri I tried to use the new option:
```
$tm_client -vv -H 172.23.177.63 -u diego -p 'mypass' microscope-file -e test_client_canonical
  upload --convert -p p1 -a a1 --directory 'path/to/files' 
```
output:
```
[ 23064/MainThread  ] 2018-01-10 16:25:57 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can re
move it from the command line.
[ 23064/MainThread  ] 2018-01-10 16:25:57 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_can
onical", plate "p1" and acquisition "a1"
[ 23064/MainThread  ] 2018-01-10 16:25:58 | INFO     | tmclient.api                             | registered 120 files
[ 23064/MainThread  ] 2018-01-10 16:26:26 | INFO     | tmclient.api                             | file uploads: 60 successful, 0 failed
```
But when I check the files being uploaded with:
```
$tm_client -vv -H 172.23.177.63 -u diego -p 'mypass' microscope-file -e test_client_canonical
 ls -p p1 -a a1
```
I get:
```
+--------------+----------+-----------------------------------------------------+
|      ID      |  Status  | Name                                                |
+--------------+----------+-----------------------------------------------------+
|   dG1hcHMx   | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A02Z01C02.FMT |
|   dG1hcHMy   | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A02Z01C02.FMT |
|   dG1hcHMz   | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A04Z01C01.FMT |
|   dG1hcHM0   | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A04Z01C01.FMT |
|   dG1hcHM1   | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A03Z01C04.FMT |
|   dG1hcHM2   | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A04Z01C01.FMT |
|   dG1hcHM3   | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A02Z01C02.FMT |
|   dG1hcHM4   | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A01Z01C03.FMT |
|   dG1hcHM5   | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A04Z01C01.FMT |
| dG1hcHMxMA== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A04Z01C05.FMT |
| dG1hcHMxMQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F010L01A04Z01C05.FMT |
| dG1hcHMxMg== | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A04Z01C05.FMT |
| dG1hcHMxMw== | WAITING  | 201703012-NUPfollowup_C22_T0001F010L01A02Z01C02.FMT |
| dG1hcHMxNA== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A03Z01C04.FMT |
| dG1hcHMxNQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A03Z01C04.FMT |
| dG1hcHMxNg== | WAITING  | 201703012-NUPfollowup_C22_T0001F006L01A04Z01C05.FMT |
| dG1hcHMxNw== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A03Z01C04.FMT |
| dG1hcHMxOA== | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A04Z01C05.FMT |
| dG1hcHMxOQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A04Z01C05.FMT |
| dG1hcHMyMA== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A04Z01C01.FMT |
| dG1hcHMyMQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A04Z01C01.FMT |
| dG1hcHMyMg== | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A03Z01C04.FMT |
| dG1hcHMyMw== | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A01Z01C03.FMT |
| dG1hcHMyNA== | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A02Z01C02.FMT |
| dG1hcHMyNQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A01Z01C03.FMT |
| dG1hcHMyNg== | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A03Z01C04.FMT |
| dG1hcHMyNw== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A02Z01C02.FMT |
| dG1hcHMyOA== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A01Z01C03.FMT |
| dG1hcHMyOQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A04Z01C05.FMT |
| dG1hcHMzMA== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A04Z01C01.FMT |
| dG1hcHMzMQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A02Z01C02.FMT |
| dG1hcHMzMg== | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A02Z01C02.FMT |
| dG1hcHMzMw== | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A04Z01C01.FMT |
| dG1hcHMzNA== | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A04Z01C05.FMT |
| dG1hcHMzNQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A01Z01C03.FMT |
| dG1hcHMzNg== | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A03Z01C04.FMT |
| dG1hcHMyNw== | WAITING  | 201703012-NUPfollowup_C22_T0001F001L01A02Z01C02.FMT |                                                               [54/1806]
| dG1hcHMyOA== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A01Z01C03.FMT |
| dG1hcHMyOQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A04Z01C05.FMT |
| dG1hcHMzMA== | WAITING  | 201703012-NUPfollowup_C22_T0001F011L01A04Z01C01.FMT |
| dG1hcHMzMQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A02Z01C02.FMT |
| dG1hcHMzMg== | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A02Z01C02.FMT |
| dG1hcHMzMw== | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A04Z01C01.FMT |
| dG1hcHMzNA== | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A04Z01C05.FMT |
| dG1hcHMzNQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A01Z01C03.FMT |
| dG1hcHMzNg== | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A03Z01C04.FMT |
| dG1hcHMzNw== | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A04Z01C01.FMT |
| dG1hcHMzOA== | WAITING  | 201703012-NUPfollowup_C22_T0001F010L01A01Z01C03.FMT |
| dG1hcHMzOQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F006L01A01Z01C03.FMT |
| dG1hcHM0MA== | WAITING  | 201703012-NUPfollowup_C22_T0001F010L01A03Z01C04.FMT |
| dG1hcHM0MQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A01Z01C03.FMT |
| dG1hcHM0Mg== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A03Z01C04.FMT |
| dG1hcHM0Mw== | WAITING  | 201703012-NUPfollowup_C22_T0001F006L01A04Z01C01.FMT |
| dG1hcHM0NA== | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A01Z01C03.FMT |
| dG1hcHM0NQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A02Z01C02.FMT |
| dG1hcHM0Ng== | WAITING  | 201703012-NUPfollowup_C22_T0001F012L01A02Z01C02.FMT |
| dG1hcHM0Nw== | WAITING  | 201703012-NUPfollowup_C22_T0001F005L01A04Z01C05.FMT |
| dG1hcHM0OA== | WAITING  | 201703012-NUPfollowup_C22_T0001F006L01A03Z01C04.FMT |
| dG1hcHM0OQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A04Z01C01.FMT |
| dG1hcHM1MA== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A02Z01C02.FMT |
| dG1hcHM1MQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F008L01A04Z01C05.FMT |
| dG1hcHM1Mg== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A04Z01C05.FMT |
| dG1hcHM1Mw== | WAITING  | 201703012-NUPfollowup_C22_T0001F007L01A03Z01C04.FMT |
| dG1hcHM1NA== | WAITING  | 201703012-NUPfollowup_C22_T0001F006L01A02Z01C02.FMT |
| dG1hcHM1NQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F010L01A04Z01C01.FMT |
| dG1hcHM1Ng== | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A04Z01C05.FMT |
| dG1hcHM1Nw== | WAITING  | 201703012-NUPfollowup_C22_T0001F004L01A01Z01C03.FMT |
| dG1hcHM1OA== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A01Z01C03.FMT |
| dG1hcHM1OQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A03Z01C04.FMT |
| dG1hcHM2MA== | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A01Z01C03.FMT |
| dG1hcHM2NA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F007L01A04Z01C01.tif |
| dG1hcHM2Ng== | COMPLETE | 201703012-NUPfollowup_C22_T0001F009L01A04Z01C01.tif |
| dG1hcHM2OA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F012L01A01Z01C03.tif |
| dG1hcHM2MQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F003L01A02Z01C02.tif |
| dG1hcHM2Mg== | COMPLETE | 201703012-NUPfollowup_C22_T0001F011L01A02Z01C02.tif |
| dG1hcHM2Mw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F005L01A04Z01C01.tif |
| dG1hcHM2NQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F008L01A03Z01C04.tif |
| dG1hcHM2Nw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F002L01A02Z01C02.tif |
| dG1hcHM1OA== | WAITING  | 201703012-NUPfollowup_C22_T0001F003L01A01Z01C03.FMT |
| dG1hcHM1OQ== | WAITING  | 201703012-NUPfollowup_C22_T0001F009L01A03Z01C04.FMT |
| dG1hcHM2MA== | WAITING  | 201703012-NUPfollowup_C22_T0001F002L01A01Z01C03.FMT |
| dG1hcHM2NA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F007L01A04Z01C01.tif |
| dG1hcHM2Ng== | COMPLETE | 201703012-NUPfollowup_C22_T0001F009L01A04Z01C01.tif |
| dG1hcHM2OA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F012L01A01Z01C03.tif |
| dG1hcHM2MQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F003L01A02Z01C02.tif |
| dG1hcHM2Mg== | COMPLETE | 201703012-NUPfollowup_C22_T0001F011L01A02Z01C02.tif |
| dG1hcHM2Mw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F005L01A04Z01C01.tif |
| dG1hcHM2NQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F008L01A03Z01C04.tif |
| dG1hcHM2Nw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F002L01A02Z01C02.tif |
| dG1hcHM2OQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F004L01A04Z01C01.tif |
| dG1hcHM3MA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F001L01A04Z01C05.tif |
| dG1hcHM3MQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F010L01A04Z01C05.tif |
| dG1hcHM3Mg== | COMPLETE | 201703012-NUPfollowup_C22_T0001F004L01A04Z01C05.tif |
| dG1hcHM3NA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F011L01A03Z01C04.tif |
| dG1hcHM3Nw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F001L01A03Z01C04.tif |
| dG1hcHM3OQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F011L01A04Z01C05.tif |
| dG1hcHM4Mg== | COMPLETE | 201703012-NUPfollowup_C22_T0001F012L01A03Z01C04.tif |
| dG1hcHM4NA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F008L01A02Z01C02.tif |
| dG1hcHM4Nw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F001L01A02Z01C02.tif |
| dG1hcHM4OQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F003L01A04Z01C05.tif |
| dG1hcHM5Mg== | COMPLETE | 201703012-NUPfollowup_C22_T0001F004L01A02Z01C02.tif |
| dG1hcHM5NA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F012L01A04Z01C05.tif |
| dG1hcHM5Nw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F012L01A04Z01C01.tif |
| dG1hcHM5OQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F006L01A01Z01C03.tif |
| dG1hcHMxMDI= | COMPLETE | 201703012-NUPfollowup_C22_T0001F003L01A03Z01C04.tif |
| dG1hcHMxMDQ= | COMPLETE | 201703012-NUPfollowup_C22_T0001F008L01A01Z01C03.tif |
| dG1hcHMxMDc= | COMPLETE | 201703012-NUPfollowup_C22_T0001F005L01A04Z01C05.tif |
| dG1hcHMxMDk= | COMPLETE | 201703012-NUPfollowup_C22_T0001F002L01A04Z01C01.tif |
| dG1hcHMxMTI= | COMPLETE | 201703012-NUPfollowup_C22_T0001F009L01A04Z01C05.tif |
| dG1hcHMxMTQ= | COMPLETE | 201703012-NUPfollowup_C22_T0001F006L01A02Z01C02.tif |
| dG1hcHMxMTc= | COMPLETE | 201703012-NUPfollowup_C22_T0001F004L01A01Z01C03.tif |
| dG1hcHMxMTk= | COMPLETE | 201703012-NUPfollowup_C22_T0001F009L01A03Z01C04.tif |
| dG1hcHM3Mw== | COMPLETE | 201703012-NUPfollowup_C22_T0001F010L01A02Z01C02.tif |
| dG1hcHM3OA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F007L01A04Z01C05.tif |
| dG1hcHM4Ng== | COMPLETE | 201703012-NUPfollowup_C22_T0001F004L01A03Z01C04.tif |
| dG1hcHMxMTU= | COMPLETE | 201703012-NUPfollowup_C22_T0001F010L01A04Z01C01.tif |
| dG1hcHM3NQ== | COMPLETE | 201703012-NUPfollowup_C22_T0001F002L01A03Z01C04.tif |
| dG1hcHM3Ng== | COMPLETE | 201703012-NUPfollowup_C22_T0001F006L01A04Z01C05.tif |
| dG1hcHM4OA== | COMPLETE | 201703012-NUPfollowup_C22_T0001F011L01A01Z01C03.tif |
...
```

**Comment by riccardomurri** [comment]
@sparkvilla can you please run the following command in your TmClient
source directory?

        git rev-parse HEAD

and then post the output here?

**Comment by sparkvilla** [comment]
@riccardomurri 78b41fafe4923cb4d2d388dde6e5cac69dd638f6

**Comment by sparkvilla** [comment]
Just tried using the previous tm_client command ( and checking for `git rev-parse HEAD`=1a9537d). I get:
```
[ 23933/MainThread  ] 2018-01-10 17:15:31 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can remove it from the command line.
[ 23933/MainThread  ] 2018-01-10 17:15:31 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_canonical", plate "p1" and acquisition "a1"
[ 23933/MainThread  ] 2018-01-10 17:15:31 | INFO     | tmclient.api                             | files will be converted to png format
[ 23933/MainThread  ] 2018-01-10 17:15:32 | INFO     | tmclient.api                             | registered 60 files

convert: no decode delegate for this image format `TIFF' @ error/constitute.c/ReadImage/509.
convert: no images defined `/run/user/1000/gvfs/smb-share:server=data.tissuemaps.org,share=tmaps-testdata-share-1/v0.3.4rc/Cellvoyager_2D_Canonical/plates/plate1/acquisitions/acquisition1/201703012-NUPfollowup_C22_T0001F003L01A02Z01C02.png' @ error/convert.c/ConvertImageCommand/3275.
[ 23933/MainThread  ] 2018-01-10 17:15:32 | ERROR    | tmclient.api                             | command '['convert', '/run/user/1000/gvfs/smb-share:server=data.tissuemaps.org,share=tmaps-testdata-share-1/v0.3.4rc/cellvoyager_2d_canonical/plates/plate1/acquisitions/acquisition1/201703012-nupfollowup_c22_t0001f003l01a02z01c02.tif', '-depth', '16', '-colorspace', 'gray', '/run/user/1000/gvfs/smb-share:server=data.tissuemaps.org,share=tmaps-testdata-share-1/v0.3.4rc/cellvoyager_2d_canonical/plates/plate1/acquisitions/acquisition1/201703012-nupfollowup_c22_t0001f003l01a02z01c02.png']' returned non-zero exit status 1
convert: no decode delegate for this image format `TIFF' @ error/constitute.c/ReadImage/509.
convert: no images defined `/run/user/1000/gvfs/smb-share:server=data.tissuemaps.org,share=tmaps-testdata-share-1/v0.3.4rc/Cellvoyager_2D_Canonical/plates/plate1/acquisitions/acquisition1/201703012-NUPfollowup_C22_T0001F010L01A02Z01C02.png' @ error/convert.c/ConvertImageCommand/3275.
```

**Comment by sparkvilla** [comment]
After reinstalling imagemagick it is all good!

**Comment by riccardomurri** [comment]
Bcc:
Reply-To:
> After reinstalling imagemagick it is all good!

Can you please try again with the latest update?
It should give a better error message if ImageMagick is not available or
does not support the needed formats.

**Comment by sparkvilla** [comment]
I am testing on a client that DOES NOT have Imagemagick installed. 
Running:
```
tm_client -vv -H 172.23.177.63 -u diego -p 'mypass' microscope-file -e test_client_canonical
  upload --convert -p p1 -a a1 --directory 'path/to/files'
```
I would expect your log error:
```
        logger.error(
            "Cannot run ImageMgick's `convert` program."
            " On Debian/Ubuntu, use `sudo apt-get install imagemagick`"
            " to install it.")
```
I get this instead:
```
[  8490/MainThread  ] 2018-01-11 08:52:02 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can remove it from the command line.
[  8490/MainThread  ] 2018-01-11 08:52:02 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_canonical", plate "p1" and acquisition "a1"
[  8490/MainThread  ] 2018-01-11 08:52:02 | ERROR    | tmclient.api                             | [errno 2] no such file or directory
```
Note: the command works without the `--convert` option

**Comment by sparkvilla** [comment]
Tried to test it on a client that DOES NOT have imagemagick installed
Running:
```
$tm_client -vvvv -H 172.23.177.63 -u diego -p 'mypass' microscope-file -e test_client_canonical
  upload --convert -p p1 -a a1 --directory 'path/to/files' 
```
Produce on the client side:
```
[  8496/MainThread  ] 2018-01-11 09:16:51 | DEBUG    | tmclient.api                             | call method "upload_microscope_files"
[  8496/MainThread  ] 2018-01-11 09:16:51 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can remove it from the command line.
[  8496/MainThread  ] 2018-01-11 09:16:51 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_canonical", plate "p1" and acquisition "a1"
Traceback (most recent call last):
  File "/home/ubuntu/venv_client/bin/tm_client", line 11, in <module>
    load_entry_point('tmclient==0.3.3', 'console_scripts', 'tm_client')()
  File "/home/ubuntu/venv_client/local/lib/python2.7/site-packages/tmclient/api.py", line 221, in __main__
    client(args)
  File "/home/ubuntu/venv_client/local/lib/python2.7/site-packages/tmclient/api.py", line 196, in __call__
    method(**kwargs)
  File "/home/ubuntu/venv_client/local/lib/python2.7/site-packages/tmclient/api.py", line 1097, in upload_microscope_files
    if not check_imagemagick_supported_format(convert):
  File "/home/ubuntu/venv_client/local/lib/python2.7/site-packages/tmclient/api.py", line 62, in check_imagemagick_supported_format
    convert_output = check_output(['convert', '--version'])
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by riccardomurri** [comment]
Should be fixed now.  Can you please update the code and try again?

**Comment by sparkvilla** [comment]
When imagemagick is not installed it is working, i.e. The exception is caught correctly. Here is the output:
```
[  8628/MainThread  ] 2018-01-11 12:02:43 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can re
move it from the command line.
[  8628/MainThread  ] 2018-01-11 12:02:43 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_can
onical_png", plate "p1" and acquisition "a1"
[  8628/MainThread  ] 2018-01-11 12:02:43 | ERROR    | tmclient.api                             | Cannot run ImageMgick's `convert` program. On Debian/Ub
untu, use `sudo apt-get install imagemagick` to install it.
[  8628/MainThread  ] 2018-01-11 12:02:43 | CRITICAL | tmclient.api                             | Aborting: conversion requested but ImageMagick's `conve
rt` not available.
```
I then installed imagemagick running `sudo apt-get install imagemagick`. Running now
```
$tm_client -vvvv -H 172.23.177.63 -u diego -p 'mypass' microscope-file -e test_client_canonical
  upload --convert -p p1 -a a1 --directory 'path/to/files'
```
gives me:
```
[ 10947/MainThread  ] 2018-01-11 12:10:30 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can remove it from the command line.
[ 10947/MainThread  ] 2018-01-11 12:10:30 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_canonical_png", plate "p1" and acquisition "a1"
[ 10947/MainThread  ] 2018-01-11 12:10:30 | ERROR    | tmclient.api                             | dictionary update sequence element #4 has length 1; 2 is required
```

**Comment by riccardomurri** [comment]
Can you please update and try again?  Should be fixed for real this time.

**Comment by sparkvilla** [comment]
Output:
```
[ 11020/MainThread  ] 2018-01-11 13:07:19 | WARNING  | tmclient.api                             | The `--directory` option is now superfluous. You can remove it from the command line.
[ 11020/MainThread  ] 2018-01-11 13:07:19 | INFO     | tmclient.api                             | upload microscope files for experiment "test_client_canonical_png", plate "p1" and acquisition "a1"
[ 11020/MainThread  ] 2018-01-11 13:07:19 | ERROR    | tmclient.api                             | 'list' object has no attribute 'split'
```

**Comment by riccardomurri** [comment]
Fixed.

**Comment by sparkvilla** [comment]
Yes, It works fine. I tested with a single dataset, but it should be sufficient. For now I'll merge it to develop

**Pull request merged**
